name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-windows-exe:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Build EXE
        shell: pwsh
        run: ./build_exe.ps1

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v5
        with:
          name: SteamGameBatchRecover-windows-exe
          path: dist/SteamGameBatchRecover/**
          if-no-files-found: error
          retention-days: 14
